- name : provision VM
  hosts: localhost

  tasks:

  - name: Using created module
    vagrant_ssh:
      path: /var/server/jenkins/slave/workspace/EPBYMINW2473/mntlab-ansible-day-Final
      state: started
    register: result

  - name: Output
    debug:
      msg: "{{result}}"

  - name: Adding host
    add_host:
      hostname: "{{result.host}}"
      ansible_connection: "ssh"
      ansible_host: "{{result.ip}}"
      ansible_port: "{{result.port}}"
      ansible_user: "{{result.username}}"
      ansible_ssh_private_key_file: "{{result.key}}"

