- import_playbook: createvm.yml
- name : Deploy
  hosts: default

  tasks:
  - name: App_deploy
    war_deploy:
      url: "{{url}}"
      war: "{{artifact}}"
      username: tomcat
      password: tomcat
      job: "{{job_name}}"
    register: result

